base_dir: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids-sv
log_dir: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids-sv/logs
tmp_dir: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids-sv/tmp

result_version: GRCh38_default
genome_version: GRCh38
genome_fa:
    GRCh38_mm10m: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids/metadata/reference/GRCh38_mm10m.fa
    GRCh38: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids/metadata/reference/GRCh38_full_analysis_set_plus_decoy_hla.fa
    mm10: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids/metadata/reference/mm10_build38_mouse.fasta
genome_mmi:
    GRCh38_mm10m: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids/metadata/reference/GRCh38_mm10m.fa.mmi
    GRCh38: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids/metadata/reference/GRCh38_full_analysis_set_plus_decoy_hla.fa.mmi
    mm10: /juno/work/shah/users/chois7/projects/drostlab/rhabdoids/metadata/reference/mm10_build38_mouse.fasta.mmi

